/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import common.MenuEnum;
import controller.Navigator;
import dto.MenuDto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    public FrMain() {
        initComponents();
        this.setTitle("Student Tracking App");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        innitCompos();
    }
    public void innitCompos(){
        Navigator navigator = new Navigator(pnMainView);
        navigator.setStartPage(pnHompage);
        final List<MenuDto> menus = new ArrayList<>();
        menus.add(new MenuDto(MenuEnum.HOMEPAGE, pnHompage, lbHomepage));
        menus.add(new MenuDto(MenuEnum.STUDENT_MANAGER, pnQuanLiHV, lbQuanLiHV));
        menus.add(new MenuDto(MenuEnum.COURSE_MANAGER, pnQuanLiKH, lbQuanLiKH));
        menus.add(new MenuDto(MenuEnum.CLASS_MANAGER, pnQuanLiLH, lbQuanLiLH));
        menus.add(new MenuDto(MenuEnum.STATISTICAL_MANAGER, pnTKDL, lbTKDL));
        navigator.setEvent(menus);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        pnApp = new javax.swing.JPanel();
        lbApp = new javax.swing.JLabel();
        pnMenu = new javax.swing.JPanel();
        pnHompage = new javax.swing.JPanel();
        lbHomepage = new javax.swing.JLabel();
        pnQuanLiHV = new javax.swing.JPanel();
        lbQuanLiHV = new javax.swing.JLabel();
        pnQuanLiKH = new javax.swing.JPanel();
        lbQuanLiKH = new javax.swing.JLabel();
        pnQuanLiLH = new javax.swing.JPanel();
        lbQuanLiLH = new javax.swing.JLabel();
        pnTKDL = new javax.swing.JPanel();
        lbTKDL = new javax.swing.JLabel();
        pnLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        pnMainView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnLeft.setBackground(new java.awt.Color(0, 255, 255));
        pnLeft.setLayout(new java.awt.BorderLayout());

        pnApp.setBackground(new java.awt.Color(204, 0, 0));
        pnApp.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), javax.swing.BorderFactory.createEmptyBorder(2, 1, 25, 1)));

        lbApp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbApp.setForeground(new java.awt.Color(255, 255, 255));
        lbApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ung_dung_white_24dp.png"))); // NOI18N
        lbApp.setText("QUẢN LÍ HỌC VIÊN");
        pnApp.add(lbApp);

        pnLeft.add(pnApp, java.awt.BorderLayout.NORTH);

        pnMenu.setBackground(new java.awt.Color(204, 204, 255));
        pnMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 12, 1, 12));
        pnMenu.setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        pnHompage.setBackground(new java.awt.Color(153, 0, 153));
        pnHompage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lbHomepage.setBackground(new java.awt.Color(102, 0, 102));
        lbHomepage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHomepage.setForeground(new java.awt.Color(255, 255, 255));
        lbHomepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu0_white_24dp.png"))); // NOI18N
        lbHomepage.setText("Màn Hình Chính");

        javax.swing.GroupLayout pnHompageLayout = new javax.swing.GroupLayout(pnHompage);
        pnHompage.setLayout(pnHompageLayout);
        pnHompageLayout.setHorizontalGroup(
            pnHompageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHomepage, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        pnHompageLayout.setVerticalGroup(
            pnHompageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHomepage, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnMenu.add(pnHompage);

        pnQuanLiHV.setBackground(new java.awt.Color(0, 153, 0));
        pnQuanLiHV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lbQuanLiHV.setBackground(new java.awt.Color(0, 153, 0));
        lbQuanLiHV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuanLiHV.setForeground(new java.awt.Color(255, 255, 255));
        lbQuanLiHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu1_white_24dp.png"))); // NOI18N
        lbQuanLiHV.setText("Quản lí học viên");

        javax.swing.GroupLayout pnQuanLiHVLayout = new javax.swing.GroupLayout(pnQuanLiHV);
        pnQuanLiHV.setLayout(pnQuanLiHVLayout);
        pnQuanLiHVLayout.setHorizontalGroup(
            pnQuanLiHVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQuanLiHV, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        pnQuanLiHVLayout.setVerticalGroup(
            pnQuanLiHVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQuanLiHV, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnMenu.add(pnQuanLiHV);

        pnQuanLiKH.setBackground(new java.awt.Color(0, 153, 0));
        pnQuanLiKH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lbQuanLiKH.setBackground(new java.awt.Color(0, 153, 0));
        lbQuanLiKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuanLiKH.setForeground(new java.awt.Color(255, 255, 255));
        lbQuanLiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu2_white_24dp.png"))); // NOI18N
        lbQuanLiKH.setText("Quản lí khóa học");

        javax.swing.GroupLayout pnQuanLiKHLayout = new javax.swing.GroupLayout(pnQuanLiKH);
        pnQuanLiKH.setLayout(pnQuanLiKHLayout);
        pnQuanLiKHLayout.setHorizontalGroup(
            pnQuanLiKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQuanLiKH, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        pnQuanLiKHLayout.setVerticalGroup(
            pnQuanLiKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQuanLiKH, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnMenu.add(pnQuanLiKH);

        pnQuanLiLH.setBackground(new java.awt.Color(0, 153, 0));
        pnQuanLiLH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lbQuanLiLH.setBackground(new java.awt.Color(0, 153, 0));
        lbQuanLiLH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuanLiLH.setForeground(new java.awt.Color(255, 255, 255));
        lbQuanLiLH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu3_white_24dp.png"))); // NOI18N
        lbQuanLiLH.setText("Quản lí lớp học");

        javax.swing.GroupLayout pnQuanLiLHLayout = new javax.swing.GroupLayout(pnQuanLiLH);
        pnQuanLiLH.setLayout(pnQuanLiLHLayout);
        pnQuanLiLHLayout.setHorizontalGroup(
            pnQuanLiLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQuanLiLH, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        pnQuanLiLHLayout.setVerticalGroup(
            pnQuanLiLHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQuanLiLH, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnMenu.add(pnQuanLiLH);

        pnTKDL.setBackground(new java.awt.Color(0, 153, 0));
        pnTKDL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lbTKDL.setBackground(new java.awt.Color(0, 153, 0));
        lbTKDL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTKDL.setForeground(new java.awt.Color(255, 255, 255));
        lbTKDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu4_white_24dp.png"))); // NOI18N
        lbTKDL.setText("Thống kê dữ liệu");

        javax.swing.GroupLayout pnTKDLLayout = new javax.swing.GroupLayout(pnTKDL);
        pnTKDL.setLayout(pnTKDLLayout);
        pnTKDLLayout.setHorizontalGroup(
            pnTKDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTKDL, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        pnTKDLLayout.setVerticalGroup(
            pnTKDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTKDL, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnMenu.add(pnTKDL);

        pnLeft.add(pnMenu, java.awt.BorderLayout.CENTER);

        pnLogo.setBackground(new java.awt.Color(204, 204, 255));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_logo_bkcit.png"))); // NOI18N

        javax.swing.GroupLayout pnLogoLayout = new javax.swing.GroupLayout(pnLogo);
        pnLogo.setLayout(pnLogoLayout);
        pnLogoLayout.setHorizontalGroup(
            pnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
        pnLogoLayout.setVerticalGroup(
            pnLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnLeft.add(pnLogo, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnLeft, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout pnMainViewLayout = new javax.swing.GroupLayout(pnMainView);
        pnMainView.setLayout(pnMainViewLayout);
        pnMainViewLayout.setHorizontalGroup(
            pnMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        pnMainViewLayout.setVerticalGroup(
            pnMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        getContentPane().add(pnMainView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbApp;
    private javax.swing.JLabel lbHomepage;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbQuanLiHV;
    private javax.swing.JLabel lbQuanLiKH;
    private javax.swing.JLabel lbQuanLiLH;
    private javax.swing.JLabel lbTKDL;
    private javax.swing.JPanel pnApp;
    private javax.swing.JPanel pnHompage;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnMainView;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnQuanLiHV;
    private javax.swing.JPanel pnQuanLiKH;
    private javax.swing.JPanel pnQuanLiLH;
    private javax.swing.JPanel pnTKDL;
    // End of variables declaration//GEN-END:variables
}
